site_name: 自修祭
site_description: 自修祭
site_author: Sakai
site_url: https://jsfes.github.io/
# google_analytics: 自修館中等教育学校

theme:
    name: material
    palette:
        scheme: preference
        # primary: white
        # primary: red
        primary: blue
        accent: green
    font:
        text: Noto Sans
    language: ja
    # logo: img/favicon.png
    # favicon: img/favicon.png
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - toc.integrate

markdown_extensions:
    - toc:
        permalink: ⚓︎
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.tabbed
    - footnotes
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
        generic: true
    - meta

plugins:
    # - tags
    - blog:
        format: "(%Y/%m/%d)"
        text-align: "right"
        articles: 5
